# Name of your application. Used to uniquely configure containers.
service: citrus_lab

# Name of the container image.
image: eastrock/citrus_lab

ssh:
  user: msh84

# Deploy to these servers.
servers:
  web:
    - 10.5.206.104
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: app.example.com
  # Proxy connects to your container on port 80 by default.
  # app_port: 5432

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: 846761448161.dkr.ecr.us-east-1.amazonaws.com/spinup-0008df/spinup-002c2e-citrus-lab
  username: AWS

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password: 
    - AWS_ECR_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
# env:
#   clear:
#     DB_HOST: spinup-db002b2b.c9ukc6s0rmbg.us-east-1.rds.amazonaws.com
#     POSTGRES_USER: eastrock
#     POSTGRES_DB: postgres
#     DB_PORT: 5432
#   secret:
#     - RAILS_MASTER_KEY

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal app logs -r job" will tail logs from the first server in the job section.
#
# aliases:
#   shell: app exec --interactive --reuse "bash"

# Use a different ssh user than root
#
# ssh:
#   user: app

# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# asset_path: /app/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
# accessories:
#   postgres:
#     image: postgres:15
#     host: spinup-db002b2b.c9ukc6s0rmbg.us-east-1.rds.amazonaws.com
#     port: 127.0.0.1:5432
#     env:
#       clear:
#         POSTGRES_DB: "postgres"
#         POSTGRES_USER: "eastrock"
#         POSTGRES_PASSWORD: "eastrockhike"
#     directories:
#       - data:/var/lib/postgresql/data
#     files:
#       - db/production_setup.sql:/docker-entrypoint-initdb.d/setup.sql
#   redis:
#     image: valkey/valkey:8
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data
